spring.application.name=blog

spring.datasource.url=jdbc:postgresql://localhost:5432/blogviajes
spring.datasource.username=postgres
spring.datasource.password=rosana

spring.datasource.driver-class-name= org.postgresql.Driver
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Cambiar update a create => spring.jpa.hibernate.ddl-auto=create-drop

spring.config.import=optional:file:.env[.properties]

# Clave secreta para JWT (debe ser larga y segura en producción)
#JWT_SECRET=asdffg
app.upload.path=uploads/